version: 0.2
phases:
  install:
    runtime-versions:
        docker: 18
    commands:
        - pip3 install --upgrade --user awscli
        - echo 'f6bd1536a743ab170b35c94ed4c7c4479763356bd543af5d391122f4af852460  yq_linux_amd64' > yq_linux_amd64.sha
        - wget https://github.com/mikefarah/yq/releases/download/4.30.8/yq_linux_amd64",
        - sha256sum -c yq_linux_amd64.sha
        - mv yq_linux_amd64 /usr/bin/yq
        - chmod +x /usr/bin/yq
      
  pre_build:
    commands:
        - cd $CODEBUILD_SRC_DIR
        - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
        - IMAGE_REPO_NAME=$repo_name
        - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
        - IMAGE_ID= $aws_account_id.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG",
                        "docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f $dockerfile .",
                        "docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_ID;",
                        "docker push $IMAGE_ID"
                      ]

  post_build:
    commands:
        - aws proton --endpoint-url https://proton.$AWS_DEFAULT_REGION.amazonaws.com --region $AWS_DEFAULT_REGION get-service --name $service_name | jq -r .service.spec > service.yaml
        - yq w service.yaml 'instances[*].spec.image' \"$IMAGE_ID\" > rendered_service.yaml
        - cat rendered_service.yaml

artifacts:
  discard-paths: yes
  files:
    # List of local artifacts that will be passed down the pipeline
    - rendered_service.yaml