version: 0.2
phases:
  install:
    runtime-versions:
        docker: 18
    commands:
        - pip3 install --upgrade --user awscli
        - wget -O /tmp/yq_linux_amd64.tar.gz https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64.tar.gz
        - tar -xvzf /tmp/yq_linux_amd64.tar.gz && mv yq_linux_amd64 /usr/bin/yq
  pre_build:
    commands:
        - cd $CODEBUILD_SRC_DIR
        - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
        - IMAGE_REPO_NAME=$repo_name
        - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
        - IMAGE_ID=$aws_account_id.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f $dockerfile .
        - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_ID;
        - docker push $IMAGE_ID

  post_build:
    commands:
        - aws proton --endpoint-url https://proton.$AWS_DEFAULT_REGION.amazonaws.com --region $AWS_DEFAULT_REGION get-service --name $service_name | jq -r .service.spec > service_spec.yaml
        - cat service_spec.yaml
        - IMAGE=$IMAGE_ID yq -i '.instances[].spec.image = strenv(IMAGE)' service_spec.yaml
        - SERVICENAME=$service_name yq -i '.instances[].servicename = strenv(SERVICENAME)' service_spec_enhanced.yaml #added servicename since it is needed by step function
        - cat service_spec_enhanced.yaml
        - yq -o=json '.' service_spec_enhanced.yaml > service_spec.json #step function takes json not yaml
        - cat service_spec.json 
        - service_spec=$(sed "s/\"/'/g" service_spec.yaml) #replaced double with single quotes
        - jq --arg service_spec "$service_spec" '. + {service_spec: [$service_spec]}' service_spec.json > build_output.json #step function needs original spec to update service instance
        - cat build_output.json

artifacts:
  discard-paths: yes
  files:
    # List of local artifacts that will be passed down the pipeline
    - build_output.json
    